{"name": "test_demo", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 1) == 3", "trace": "function_before = 'hello'\n\n    def test_demo(function_before):\n        # 使用夹具名称直接获取函数返回值\n        print(function_before)\n>       assert 1 + 1 == 3\nE       assert (1 + 1) == 3\n\ntest_fixture.py:32: AssertionError"}, "attachments": [{"name": "stdout", "source": "0588a201-71f9-4939-b5e8-af9785238ab6-attachment.txt", "type": "text/plain"}], "start": 1610243723119, "stop": 1610243723119, "uuid": "206a3b29-08ff-45d1-b97a-5ec541cd20fa", "historyId": "7c39183f9b5c8abdeda289757f98b8b5", "testCaseId": "3510fbf806743f5ce9c2d2153db9d90c", "fullName": "test_fixture#test_demo", "labels": [{"name": "suite", "value": "test_fixture"}, {"name": "host", "value": "DESKTOP-15NEG78"}, {"name": "thread", "value": "41740-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture"}]}