{"name": "test_demo", "status": "failed", "statusDetails": {"message": "AssertionError: assert (1 + 1) == 3", "trace": "function_before = 'hello'\n\n    def test_demo(function_before):\n        # 使用夹具名称直接获取函数返回值\n        print(function_before)\n>       assert 1 + 1 == 3\nE       assert (1 + 1) == 3\n\ntest_fixture.py:32: AssertionError"}, "attachments": [{"name": "stdout", "source": "c637e296-e394-4712-a4d5-6e751cb10bd8-attachment.txt", "type": "text/plain"}], "start": 1610204427656, "stop": 1610204427657, "uuid": "1ec8df9f-2978-482e-b730-eaa9e3b3eb33", "historyId": "7c39183f9b5c8abdeda289757f98b8b5", "testCaseId": "3510fbf806743f5ce9c2d2153db9d90c", "fullName": "test_fixture#test_demo", "labels": [{"name": "suite", "value": "test_fixture"}, {"name": "host", "value": "DESKTOP-15NEG78"}, {"name": "thread", "value": "33056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture"}]}